# Generated by Django 5.1.7 on 2025-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='connectivity_graph',
            field=models.JSONField(blank=True, help_text='JSON graph data representing connectivity between rooms', null=True),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='room_details',
            field=models.JSONField(blank=True, help_text='JSON data with room IDs and their coordinates', null=True),
        ),
    ]
